# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_collocationfile_metafile_wordfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word2VecFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to='')),
                ('syn1neg', models.FileField(upload_to='')),
                ('vectors', models.FileField(upload_to='')),
            ],
        ),
    ]
